server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tomato_notify?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: tomato
    password: tomato
  rabbitmq:
    host: 127.0.0.1  # 设置RabbitMQ所在主机
    port: 5672       # 设置RabbitMQ服务端口
    username: guest  # 设置RabbitMQ用户名
    password: guest  # 设置RabbitMQ密码
    connection-timeout: 5000
    listener:
      simple:
        concurrency: 5 # 每个listener在初始化的时候设置的并发消费者的个数
        max-concurrency: 10 # 最大并发数量
        acknowledge-mode: manual # 开启手动签收
        prefetch: 1 # 每次一次性从broker里面取的待消费的消息的个数
    # 如果没有抵达队列,以异步发送优先回调returns确认
    template:
      mandatory: true
    publisher-confirm-type: simple
    # 动态创建和绑定队列、交换机的配置
    rabbitInfoList:
      ## 延迟队列配置
      - routing-key: order.notify.delay.routing.key
        queue:
          name: order.notify.delay.queue
        exchange:
          name: order.notify.delay.exchange
          type: DELAYED
          arguments:
            x-delayed-type: topic
mybatis:
  type-aliases-package: com.tomato.notify.database.dataobject
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    org.springframework.web: INFO