spring:
  # 网关 + 授权服务器注册的OAuth2客户端，它需要配置到资源服务器的路由规则和令牌中继功能
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          # 配置RSA的公钥访问地址
#          jwk-set-uri: ${auth.server-url}/oauth2/jwks
  redis:
    timeout: PT30S
    client-type: lettuce
    database: 0
    host: ${redis.host}
    port: ${redis.port}
    lettuce:
      pool:
        # 连接池最小空闲连接数
        min-idle: 1
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          lower-case-service-id: true
      # 路由数组：指当请求满足什么样的断言时，转发到哪个服务上
      routes: # 负载均衡 路由代理
        # 路由标识，要求唯一，名称任意
        - id: tomato-module-skill  # 唯一的serviceId
          uri: lb://tomato-module-skill # lb://为固定写法，表示开启负载均衡；tomato-module-skill 即服务在注册的名字
          predicates:
            - Path=/tomato-module-skill/** # 匹配转发路由
          filters: # 跳过指定路径
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                # 令牌桶每秒填充平均速率,即行等价于允许用户每秒处理多少个请求平均数
                redis-rate-limiter.replenishRate: 1
                # 令牌桶的容量，允许在一秒钟内完成的最大请求数
                redis-rate-limiter.burstCapacity: 2
                # 用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
                key-resolver: "#{@apiKeyResolver}"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

# Ribbon 配置
ribbon:
  ReadTimeout: 5000 # 请求连接的超时时间
  ConnectTimeout: 10000 # 请求处理的超时时间
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1



# Feign 配置
feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  sentinel:  # 开启feign对sentinel的支持
    enabled: false 