
-- ----------------------------
--
-- ----------------------------
CREATE DATABASE IF NOT EXISTS tomato_id DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

CREATE DATABASE IF NOT EXISTS tomato_skill DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

CREATE DATABASE IF NOT EXISTS tomato_auth DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

CREATE DATABASE IF NOT EXISTS tomato_sys DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;

CREATE DATABASE IF NOT EXISTS tomato_account DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;