DROP TABLE IF EXISTS `oms_order`;
CREATE TABLE `oms_order`  (
      `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'id',
      `order_sn` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '订单号',
      `total_amount` bigint NOT NULL DEFAULT 0 COMMENT '订单总额（分）',
      `total_quantity` int NOT NULL DEFAULT 0 COMMENT '商品总数',
      `source_type` tinyint NOT NULL DEFAULT 1 COMMENT '订单来源[0->PC订单；1->APP订单]',
      `status` int NOT NULL DEFAULT 101 COMMENT '订单状态：\r\n101->待付款；\r\n102->用户取消；\r\n103->系统取消；\r\n201->已付款；\r\n202->申请退款；\r\n203->已退款；\r\n301->待发货；\r\n401->已发货；\r\n501->用户收货；\r\n502->系统收货；\r\n901->已完成；',
      `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '' COMMENT '订单备注',
      `member_id` bigint NOT NULL DEFAULT 0 COMMENT '会员id',
      `coupon_id` bigint NOT NULL DEFAULT 0 COMMENT '使用的优惠券',
      `coupon_amount` bigint NOT NULL DEFAULT 0 COMMENT '优惠券抵扣金额（分）',
      `freight_amount` bigint NOT NULL DEFAULT 0 COMMENT '运费金额（分）',
      `pay_amount` bigint NOT NULL DEFAULT 0 COMMENT '应付总额（分）',
      `pay_time` datetime NULL DEFAULT NULL COMMENT '支付时间',
      `pay_type` tinyint NULL DEFAULT NULL COMMENT '支付方式【1->微信jsapi；2->支付宝；3->余额； 4->微信app；】',
      `out_trade_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '微信支付等第三方支付平台的商户订单号',
      `transaction_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '微信支付订单号',
      `out_refund_no` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '商户退款单号',
      `refund_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '微信退款单号',
      `delivery_time` datetime NULL DEFAULT NULL COMMENT '发货时间',
      `receive_time` datetime NULL DEFAULT NULL COMMENT '确认收货时间',
      `comment_time` datetime NULL DEFAULT NULL COMMENT '评价时间',
      `deleted` tinyint(1) NULL DEFAULT 0 COMMENT '逻辑删除【0->正常；1->已删除】',
      `gmt_create` datetime NULL DEFAULT NULL COMMENT '创建时间',
      `gmt_modified` datetime NULL DEFAULT NULL COMMENT '修改时间',
      PRIMARY KEY (`id`) USING BTREE,
      UNIQUE INDEX `index_order_sn`(`order_sn`) USING BTREE COMMENT '订单号唯一索引',
      UNIQUE INDEX `index_otn`(`out_trade_no`) USING BTREE COMMENT '商户订单号唯一索引',
      UNIQUE INDEX `index_ti`(`transaction_id`) USING BTREE COMMENT '商户支付单号唯一索引',
      UNIQUE INDEX `index_orn`(`out_refund_no`) USING BTREE COMMENT '商户退款单号唯一索引',
      UNIQUE INDEX `index_ri`(`refund_id`) USING BTREE COMMENT '退款单号唯一索引'
) ENGINE = InnoDB AUTO_INCREMENT = 1351548262424821956 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '订单详情表' ROW_FORMAT = DYNAMIC;

DROP TABLE IF EXISTS `oms_order`;
CREATE TABLE `oms_order` (
     `member_id` bigint(20) NOT NULL,
     `coupon_id` bigint(20) DEFAULT NULL,
     `order_sn` varchar(64) DEFAULT NULL COMMENT '订单编号',
     `create_time` datetime DEFAULT NULL COMMENT '提交时间',
     `member_username` varchar(64) DEFAULT NULL COMMENT '用户帐号',
     `total_amount` decimal(10,2) DEFAULT NULL COMMENT '订单总金额',
     `pay_amount` decimal(10,2) DEFAULT NULL COMMENT '应付金额（实际支付金额）',
     `freight_amount` decimal(10,2) DEFAULT NULL COMMENT '运费金额',
     `promotion_amount` decimal(10,2) DEFAULT NULL COMMENT '促销优化金额（促销价、满减、阶梯价）',
     `integration_amount` decimal(10,2) DEFAULT NULL COMMENT '积分抵扣金额',
     `coupon_amount` decimal(10,2) DEFAULT NULL COMMENT '优惠券抵扣金额',
     `discount_amount` decimal(10,2) DEFAULT NULL COMMENT '管理员后台调整订单使用的折扣金额',
     `pay_type` int(1) DEFAULT NULL COMMENT '支付方式：0->未支付；1->支付宝；2->微信',
     `source_type` int(1) DEFAULT NULL COMMENT '订单来源：0->PC订单；1->app订单',
     `status` int(1) DEFAULT NULL COMMENT '订单状态：0->待付款；1->待发货；2->已发货；3->已完成；4->已关闭；5->无效订单',
     `order_type` int(1) DEFAULT NULL COMMENT '订单类型：0->正常订单；1->秒杀订单',
     `delivery_company` varchar(64) DEFAULT NULL COMMENT '物流公司(配送方式)',
     `delivery_sn` varchar(64) DEFAULT NULL COMMENT '物流单号',
     `auto_confirm_day` int(11) DEFAULT NULL COMMENT '自动确认时间（天）',
     `integration` int(11) DEFAULT NULL COMMENT '可以获得的积分',
     `growth` int(11) DEFAULT NULL COMMENT '可以活动的成长值',
     `promotion_info` varchar(100) DEFAULT NULL COMMENT '活动信息',
     `bill_type` int(1) DEFAULT NULL COMMENT '发票类型：0->不开发票；1->电子发票；2->纸质发票',
     `bill_header` varchar(200) DEFAULT NULL COMMENT '发票抬头',
     `bill_content` varchar(200) DEFAULT NULL COMMENT '发票内容',
     `bill_receiver_phone` varchar(32) DEFAULT NULL COMMENT '收票人电话',
     `bill_receiver_email` varchar(64) DEFAULT NULL COMMENT '收票人邮箱',
     `receiver_name` varchar(100) NOT NULL COMMENT '收货人姓名',
     `receiver_phone` varchar(32) NOT NULL COMMENT '收货人电话',
     `receiver_post_code` varchar(32) DEFAULT NULL COMMENT '收货人邮编',
     `receiver_province` varchar(32) DEFAULT NULL COMMENT '省份/直辖市',
     `receiver_city` varchar(32) DEFAULT NULL COMMENT '城市',
     `receiver_region` varchar(32) DEFAULT NULL COMMENT '区',
     `receiver_detail_address` varchar(200) DEFAULT NULL COMMENT '详细地址',
     `note` varchar(500) DEFAULT NULL COMMENT '订单备注',
     `confirm_status` int(1) DEFAULT NULL COMMENT '确认收货状态：0->未确认；1->已确认',
     `delete_status` int(1) NOT NULL DEFAULT '0' COMMENT '删除状态：0->未删除；1->已删除',
     `use_integration` int(11) DEFAULT NULL COMMENT '下单时使用的积分',
     `payment_time` datetime DEFAULT NULL COMMENT '支付时间',
     `delivery_time` datetime DEFAULT NULL COMMENT '发货时间',
     `receive_time` datetime DEFAULT NULL COMMENT '确认收货时间',
     `comment_time` datetime DEFAULT NULL COMMENT '评价时间',
     `modify_time` datetime DEFAULT NULL COMMENT '修改时间',
     PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8 COMMENT='订单表';


DROP TABLE IF EXISTS `tz_order`;

CREATE TABLE `tz_order` (
    `shop_id` bigint(20) DEFAULT NULL COMMENT '店铺id',
    `prod_name` varchar(1000) NOT NULL DEFAULT '' COMMENT '产品名称,多个产品将会以逗号隔开',
    `user_id` varchar(36) NOT NULL COMMENT '订购用户ID',
    `order_number` varchar(50) NOT NULL COMMENT '订购流水号',
    `total` decimal(15,2) NOT NULL DEFAULT '0.00' COMMENT '总值',
    `actual_total` decimal(15,2) DEFAULT NULL COMMENT '实际总值',
    `pay_type` int(1) DEFAULT NULL COMMENT '支付方式 0 手动代付 1 微信支付 2 支付宝',
    `remarks` varchar(1024) DEFAULT NULL COMMENT '订单备注',
    `status` int(2) NOT NULL DEFAULT '0' COMMENT '订单状态 1:待付款 2:待发货 3:待收货 4:待评价 5:成功 6:失败',
    `dvy_type` varchar(10) DEFAULT NULL COMMENT '配送类型',
    `dvy_id` bigint(20) DEFAULT NULL COMMENT '配送方式ID',
    `dvy_flow_id` varchar(100) DEFAULT '' COMMENT '物流单号',
    `freight_amount` decimal(15,2) DEFAULT '0.00' COMMENT '订单运费',
    `addr_order_id` bigint(20) DEFAULT NULL COMMENT '用户订单地址Id',
    `product_nums` int(10) DEFAULT NULL COMMENT '订单商品总数',
    `create_time` datetime NOT NULL COMMENT '订购时间',
    `update_time` datetime DEFAULT NULL COMMENT '订单更新时间',
    `pay_time` datetime DEFAULT NULL COMMENT '付款时间',
    `dvy_time` datetime DEFAULT NULL COMMENT '发货时间',
    `finally_time` datetime DEFAULT NULL COMMENT '完成时间',
    `cancel_time` datetime DEFAULT NULL COMMENT '取消时间',
    `is_payed` tinyint(1) DEFAULT NULL COMMENT '是否已经支付，1：已经支付过，0：，没有支付过',
    `delete_status` int(1) DEFAULT '0' COMMENT '用户订单删除状态，0：没有删除， 1：回收站， 2：永久删除',
    `refund_sts` int(1) DEFAULT '0' COMMENT '0:默认,1:在处理,2:处理完成',
    `reduce_amount` decimal(15,2) DEFAULT NULL COMMENT '优惠总额',
    `order_type` tinyint(2) DEFAULT NULL COMMENT '订单类型',
    `close_type` tinyint(2) DEFAULT NULL COMMENT '订单关闭原因 1-超时未支付 2-退款关闭 4-买家取消 15-已通过货到付款交易',
    UNIQUE KEY `order_number_unique_ind` (`order_number`),
    UNIQUE KEY `order_number_userid_unique_ind` (`user_id`,`order_number`),
    KEY `shop_id` (`shop_id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='订单表';